name: nitrogen6
version: 18-0.1
summary: i.Mx6 Nitrogen6 gadget
description: |
 Bootloader files and partitoning data to create a
 bootable Ubuntu Core 18 image for the nitrogen6.
type: gadget
base: core18
architectures:
  - build-on: amd64
    run-on: armhf
confinement: strict
grade: stable

parts:
  uboot:
    plugin: make
    source: git://git.denx.de/u-boot.git
    source-branch: v2018.11
    artifacts: [u-boot.imx]
    override-build: |
      git apply -v ../../../uboot.patch
      TCHAINVER="$(wget -q -O - \
                 https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/| \
                 html2text -width 200|grep 'x86_64_arm-linux-gnueabihf.tar.xz '|cut -d' ' -f2)"
      wget https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/$TCHAINVER
      tar xf $TCHAINVER
      mv $(echo $TCHAINVER|sed 's/.tar.xz$//') toolchain
      CROSS_COMPILE=$(pwd)/toolchain/bin/arm-linux-gnueabihf- make nitrogen6q2g_defconfig
      CROSS_COMPILE=$(pwd)/toolchain/bin/arm-linux-gnueabihf- make
      mkdir -p $SNAPCRAFT_PART_INSTALL/boot-assets
      cp u-boot.imx $SNAPCRAFT_PART_INSTALL/boot-assets
      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      cd $SNAPCRAFT_PART_INSTALL; ln -s uboot.env uboot.conf
    build-packages:
      - libpython2.7-dev
      - build-essential
      - bc
      - wget
      - on amd64:
        - gcc-arm-linux-gnueabihf
    build-packages:
      - cpio
      - findutils
      - xz-utils
      - gcc-arm-linux-gnueabihf:amd64
      - html2text
      - bison
      - flex

slots:
  i2c-0:
    interface: i2c
    path: /dev/i2c-0
  i2c-1:
    interface: i2c
    path: /dev/i2c-1
  i2c-2:
    interface: i2c
    path: /dev/i2c-2
